config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'batches/preview/:id', to: "batches#preview", as: 'batch_preview'
  get 'batches/preview/:id/progress', to: "batches#progress", as: 'batch_progress'
  resources :batches

  post 'import', to: "leads#import", as: 'import_leads'
  resources :leads

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get 'start', to: "registrations#start", as: 'start'
    get 'signup', to: "registrations#new", as: 'signup'
    get 'login', to: "sessions#new", as: 'login'
    get 'settings', to: "registrations#edit", as: 'settings'
    delete 'logout', to: "sessions#destroy", as: 'logout'
  end

end

app/models/batch.rb
class Batch < ActiveRecord::Base
  has_many :leads, dependent: :destroy

  before_create :generate_uuid

  def generate_uuid
    self.uuid = loop do
      random_uuid = SecureRandom.hex(16)
      break random_uuid unless self.class.exists?(uuid: random_uuid)
    end
  end
end

app/models/lead.rb
class Lead < ActiveRecord::Base
  belongs_to :batch

  def self.import(file, batch_id)
    ImportLeadsJob.perform_async(file, batch_id)
  end

  def self.to_csv(options = {})
      delete_list = ['id', 'created_at', 'updated_at', 'batch_id', 'extended']
      new_columns = column_names - delete_list

      CSV.generate(options) do |csv|
        lead = all.first
        csv << new_columns + lead.extended.keys

        all.each do |lead|
          extended_values = lead.extended.keys
          csv << lead.attributes.values_at(*new_columns) + lead.extended.values_at(*extended_values)
        end
      end
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :set_user

	def set_user
		@user = current_user if current_user
	end

	# def after_sign_in_path_for(resource)
	# 	(if something true) ? send_user_here : send_user_elsewhere
	# end

end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  before_action :set_batch, only: [:edit, :show, :preview, :progress]

  def new
    @batch = Batch.create!
    redirect_to edit_batch_path(@batch.uuid)
  end

  def edit
  end

  def show
    @batch_uuid = @batch.uuid
    @leads = @batch.leads[0..15]
    @lead_count = @batch.lead_count
    @duplicate_count = @batch.duplicate_count
    @error_count = @batch.error_count
    @extended_attributes = @leads.try(:first).try(:extended).try(:keys) || []

    respond_to do |format|
      format.html
      format.csv { send_data @batch.leads.to_csv, filename: "leads-#{Date.today}.csv" }
    end
  end

  def preview
    @uuid = @batch.uuid
    @lead_count = @batch.lead_count
  end

  def progress
    completed = @batch.leads.count
    render json: {status: 'ok', completed: completed}
  end

  def create
    @batch = Batch.new(batch_params)

    respond_to do |format|
      if @batch.save
        format.html { redirect_to edit_batch_path(@batch.uuid) }
        format.json { render :show, status: :created, location: @batch }
      else
        format.html { render :new }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_batch
      @batch = Batch.find_by(uuid: params[:id])
      return unless @batch.uuid.length == 32

      # wrong uuid, hacker, primary key attempt, etc
      rescue
      redirect_to root_path
    end

    def batch_params
      params.fetch(:batch, {})
    end

end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController

  def import
    batch = Batch.find(params[:batch_id])

    # store intended leads count being uploaded, for progress bar on :show
    lead_count = CSV.read(params[:file].path, headers: true, encoding:'iso-8859-1:utf-8', skip_blanks: true, skip_lines: /^(?:,\s*)+$/).count
    batch.update(lead_count: lead_count)

    Lead.import(params[:file], batch.id)
    # redirect_to batch_path(batch.uuid)
    redirect_to batch_preview_path(batch.uuid)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @batch = Batch.new
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

# custom Devise override code here

private
  def sign_up_params
    params.require(:user).permit(:email, :password)
  end

  def account_update_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

# custom Devise override code here

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/batches/edit.html.erb
<%= form_tag import_leads_path(batch_id: @batch.id), id: 'import-form', class: 'gap', multipart: true do %>

<label class="btn btn-lg btn-default btn-file">
    <h1>Import your leads</h1>
    Click to Upload
    <%= file_field_tag :file %>
</label>
  <div class="row gap">
    <%= submit_tag "Sanitize", class: "btn btn-lg btn-primary", id: 'submit', style: 'display:none', data: {'disable-with' => 'Please wait...'} %>
  </div>
<% end %>


<script>
  $(function() {
    $('input#file').click(function() {
      $('#submit').show();
    })
  })
</script>

app/views/batches/preview.html.erb
<% meta title: "Now Importing...", description: "View your cold email sanitization progress." %>

<h1>Your sanitization is in progress.</h1><br>

<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
</div>

<script>
  $(function() {
    var uuid = '<%= @uuid %>';
    var intended_count = '<%= @lead_count %>';
    var current_count = 0;

    var i = setInterval(function(){
      $.ajax({
        url: uuid + '/progress',
        method: 'get',
        contentType: 'json',
        success: function(data) {
          if (current_count == data.completed) {
            var batch = "/batches/" + uuid + '/';
            window.location.href = batch; // redirect to show batch if stalling
          }

          current_count = data.completed;
          var completion = Math.round((data.completed / intended_count)*100);
          $('.progress-bar').css('width', completion + '%');
          $('.progress-bar').text(completion + '%');

          if (data.completed == intended_count) {
            clearInterval(i);
            var batch = "/batches/" + uuid + '/';
            window.location.href = batch; // redirect to show batch if complete
          }
        }
      })
    }, 200)

  })
</script>

app/views/batches/show.html.erb
<% meta title: "View your Leads", description: "Download your cold email leads." %>

<h1 style="text-align: center">Congrats, you're all set.</h1>

<div class="what-was-done">
  <h3>We processed <span><%= @lead_count %></span> leads, found <span><%= @duplicate_count %></span> duplicates, and had <span><%= @errors || 0 %></span> failures.</h3>

  <ul>
    <li>We created a column, 'first name', that has proper casing for all the names you provided.</li>
    <li>Removed common legal terms like 'Corp, Inc, LLC', etc and their many variants.</li>
    <li>Skipped leads that were missing an email.</li>
    <li>If no name was found we used 'there', so you can still email "hey there..."</li>
  </ul>
</div>

<p class="table-header">
  <%= link_to 'download my leads', "/batches/#{@batch_uuid}.csv", class: 'btn btn-success' %>
</p>

<table class="table table-striped table-hover">

  <thead>
    <th>First Name</th>
    <th>Email Address</th>
    <th>Company Name</th>
    <% @extended_attributes.each do |attribute| %>
      <th><%= attribute %></th>
    <% end %>
  </thead>

  <tbody>
    <% @leads.each do |lead| %>
      <tr>
        <td class="sanitized"><%= lead.first_name %></td>
        <td class="sanitized"><%= lead.email_address %></td>
        <td class="sanitized"><%= lead.company_name %></td>

        <% extended_attributes = lead.extended %>
        <% extended_attributes.each do |attribute| %>
          <td><%= attribute[1] %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>

</table>

<p class="table-footer">Don't worry, the rest of your leads are here, just hidden to save page load time.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= metamagic site: "Friendly CSV", title: [:site, :title], separator: " | " %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/header" %>
  <div class="container">
    <%= yield %>
  </div>
</body>
<footer>
  <%= render "shared/footer" %>
</footer>
</html>

app/views/pages/home.html.erb
<% meta title: "Sanitize Cold Email Prospects", description: "Upload a list of cold email outreach prospects to automatically clean up the merge variables. 100% Free. Click to learn more." %>

<div class="jumbotron">
  <h1>Warm up your cold email</h1><br>
  <p>Sanitize popular merge variables before you hit send</p>
  <%= simple_form_for(@batch) do |f| %>
    <%= f.submit class: "btn btn-primary", value: 'upload a csv' %>
  <% end %>
</div>


<div class="pitch">
  <div class="col-md-4">
    <h3>Huh?</h3>
    <p>You scrape contact information. It looks like shit. This tool cleans it up before you start embarassing yourself.</p>
  </div>
  <div class="col-md-4">
    <h3>How does it work?</h3>
    <p>This removes garbage from company names (ie: 'LLC') and fixes people names too. And some other stuff.</p>
  </div>
  <div class="col-md-4">
    <h3>What's the catch?</h3>
    <p>No catch. Not yet. Doesn't even require your email, just import and export. Whole thing takes seconds.</p>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer" style="text-align:center" id="footer">
  <div class="row">
    <small>made by <%= link_to 'ryan kulp', 'http://www.ryanckulp.com', target: '_blank' %></small>
  </div>
</div>

<!-- google analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-68093300-12', 'auto');
  ga('send', 'pageview');

</script>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header-collapse" role="navigation">
      <%= link_to 'FriendlyCSV', root_path, class: 'navbar-brand' %>
    </div>
  </div>
</nav>